# Generated by Django 3.2.5 on 2022-05-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcontent',
            field=models.TextField(blank=True),
        ),
    ]
