# Generated by Django 3.2.5 on 2022-07-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_subcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='postimages'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcontent',
            field=models.TextField(blank=True, max_length=450),
        ),
    ]
