# Generated by Django 3.2.5 on 2022-07-26 04:54

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0070_userprofile'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0023_auto_20220708_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', models.CharField(max_length=120)),
                ('author', models.CharField(default='Courage', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sketch', 'Sketch')], default='draft', max_length=10)),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('song', 'Song'), ('other', 'Other')], default='blog', max_length=20)),
                ('post_slug', models.SlugField(max_length=1100, unique_for_date='created')),
                ('comments', models.BooleanField(default=True)),
                ('post_image', models.ImageField(blank=True, upload_to='postimages')),
                ('content', models.TextField()),
                ('subcontent', models.TextField(blank=True, max_length=450)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
