# Generated by Django 3.2.5 on 2022-07-26 05:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='header',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.fields.RichTextField(),
        ),
    ]
